### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by ynks** [ynks/Hell-Shooter#12]
- [x] Player shooting
- [x] Enemy shooting
- [x] Player Thruster
- [x] Player hit enemy
- [x] Enemy breaks
- [x] Enemy hit player
- [x] Enemy hit shield
- [x] Shield up
- [x] Shield down
- [x] Ability Ready
- [ ] Player dies or Loose sound
- [x] Dash SFX
- [ ] Open stat menu
- [ ] Closed stat menu
- [ ] Stat pucharsed
- [ ] Stat sold
- [ ] Open shop
- [ ] Closed shop
- [ ] Part equiped
- [ ] Part unequiped
- [ ] Part pucharsed
- [ ] Stage clear or Stage begins
- [ ] Win sound
- [ ] Level Up Sound

**Comment by dariormt** [comment]
Main Gameplay SFX are done, waiting for HUD to complete #18

**Comment by dariormt** [comment]
Closing this, we´ll continue in #85
